# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazysql < Formula
  desc ""
  homepage "https://github.com/jorgerojas26/lazysql"
  version "0.2.5"

  on_macos do
    on_intel do
      url "https://github.com/jorgerojas26/lazysql/releases/download/v0.2.5/lazysql_Darwin_x86_64.tar.gz"
      sha256 "03f0ae207285e5c4dfe49de43c398976b02e19f959800a49f8346767cb10ccf8"

      def install
        bin.install "lazysql"
      end
    end
    on_arm do
      url "https://github.com/jorgerojas26/lazysql/releases/download/v0.2.5/lazysql_Darwin_arm64.tar.gz"
      sha256 "688834f4ed87a4dc17d5e420dc6975d07939e7b3c20d4c2363896ee282f3ab24"

      def install
        bin.install "lazysql"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jorgerojas26/lazysql/releases/download/v0.2.5/lazysql_Linux_x86_64.tar.gz"
        sha256 "6571be509e02774395faf77756cf856f6c2aefe570b75ea40d20269bbc28aaa6"

        def install
          bin.install "lazysql"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jorgerojas26/lazysql/releases/download/v0.2.5/lazysql_Linux_arm64.tar.gz"
        sha256 "0971fb0d98db1d55f8632775bdc3ae5d2989313a87f07cb30e6f4bf6c704abbb"

        def install
          bin.install "lazysql"
        end
      end
    end
  end

  test do
    system "#{bin}/lazysql version"
  end
end
