# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazysql < Formula
  desc ""
  homepage "https://github.com/jorgerojas26/lazysql"
  version "0.2.3"

  on_macos do
    on_intel do
      url "https://github.com/jorgerojas26/lazysql/releases/download/v0.2.3/lazysql_Darwin_x86_64.tar.gz"
      sha256 "df55f5522d7a510f21cc62a758e6aad50c50f51e03e5857e5cc7b721136e420e"

      def install
        bin.install "lazysql"
      end
    end
    on_arm do
      url "https://github.com/jorgerojas26/lazysql/releases/download/v0.2.3/lazysql_Darwin_arm64.tar.gz"
      sha256 "fc81013d6c3b2491631b7891ada90e316ad09c5300e7eb94541e808bfa78ea66"

      def install
        bin.install "lazysql"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jorgerojas26/lazysql/releases/download/v0.2.3/lazysql_Linux_x86_64.tar.gz"
        sha256 "3069efc90485f45ddd1101acbf54538811a888ce560c418274183a516f0d9f1b"

        def install
          bin.install "lazysql"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jorgerojas26/lazysql/releases/download/v0.2.3/lazysql_Linux_arm64.tar.gz"
        sha256 "61cfe2acd748283a67011714d251e8780b4883d5506cc02fb003939d32e817b2"

        def install
          bin.install "lazysql"
        end
      end
    end
  end

  test do
    system "#{bin}/lazysql version"
  end
end
